[workspace]
members = [
    "client/core",
    "client/noise-kv",
    "apps/cmdline-lightswitch",
]

[profile.release]
opt-level = 3

[profile.release-lto]
inherits = "release"
lto = true
strip = true