[workspace]
members = [
    "client/core",
    "client/wasm-compat-core",
    "client/sequential-noise-kv",
    "client/serializable-noise-kv",
    "apps/cmdline-lightswitch",
    "apps/cmdline-period-tracking",
]
