[workspace]
members = [
    "client/core",
    "client/sequential-noise-kv",
    "client/serializable-noise-kv",
    "client/merged-serializable-noise-kv",
    "apps/cmdline-skeleton",
    "apps/cmdline-lightswitch",
    "apps/cmdline-period-tracking",
    "apps/cmdline-chess",
    "apps/cmdline-social-media",
    "apps/cmdline-password-manager",
    "apps/cmdline-calendar",
]
